### ISSUE TITLE
[Splash Screen] Flicker Between Controller And Keyboard in all the Games

### ISSUE THREAD

**Issue by RangerXR1** [darklinkpower/PlayniteExtensionsCollection#103]
Extension
Splash Screen

Describe the bug
In Full Screen When I open a game using controller at first it will work normally but when i exit that game and again open another game the controller flickers between keyboard and Controller. And double jump in the menu screen. But the problem will solve if  i disable the splash screen extension. and the controller work normally after multiple relaunch of the Game

To Reproduce
Enable Splash Screen - Open Playnite in fullscreen - Launch any Game - Exit the game in the menu - Reopen the same game - The controller will be bugging out.

Expected behavior
The Controller should function normally while using the extension.. 
Detailed Video Of the issue : 
https://youtu.be/Vpwdo03kIb0
[](https://youtu.be/Vpwdo03kIb0)

**Comment by Gildum** [comment]
I just notcied this issue aswell. First I thought the specific game was having gamepad issues, but then I read your post. I tried it with a few games and the same issue appears there too. In my case it appears immediately the first I launch a game after starting Playnite Fullscreen.

It seems like a directional input of the dpad and analog stick results in a double output, example:
- I press down on the gamepad's dpad
- the game registers it as "dpad down" input
- aswell as "keyboard arrow-down" input
- for example when browsing in menus, this results in moving down 2 menu entries instead of 1

**Comment by Gildum** [comment]
The issue has also already been reported here:
https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/75

**Comment by RangerXR1** [comment]
Is there any way to fix this bugs. I really Like splash screen but it is annoying every time restarting playnite before lanuching another game.

**Comment by Gildum** [comment]
Yes it looks like this issue was introduced with playnite 9, and is a bug in general, not just related to the splash screen extension:

https://github.com/JosefNemec/Playnite/issues/2593
https://playnite.link/forum/thread-935.html

This probably means if this issue is fixed in playnite itself, the fullscreen splash screen issue will also autoamtically be fixed.

**Comment by Gildum** [comment]
I'm don't know if it's any help in solving the issue, but I wanted to mention that via Autohotkey, it's possible to create a splash screen image script that acts just like darklinkpower's splash screen image function, without any input issues occuring in fullscreen mode. Here is a simple black splashscreen as an example:

```
Gui,Color,Black,000000
Gui, -Caption
Gui, Margin , 0, 0
Gui,Show, x0 y0 h%A_ScreenHeight% w%A_ScreenWidth%
```

It's possible to choose any custom image as the splashscreen image and even include a fade in/out transition just like the Splash Screen extension. Maby it's possible to adjust the Splash Screen extension to work more similar to the autohotkey solution, which could then potentially fix the input issue.

**Comment by darklinkpower** [comment]
Closing since this is fixed as of the latest Playnite release.

There's currently a bug with controllers not working in Fullscreen mode after Playnite restores itself but have not been able to find a fix and I'm not sure if this should be fixed on the extension or Playnite's side.

As a workaround, this can be fixed by adding this global script for game close in Playnite options

```
if ($PlayniteApi.ApplicationInfo.Mode -eq "Fullscreen")
{
    $wshell = New-Object -ComObject wscript.shell
    $wshell.SendKeys('%{TAB}')

    #To not send keys too quickly
    Start-Sleep -Milliseconds 1000

    $wshell.SendKeys('%{TAB}')
}
```
