### ISSUE TITLE
[Extra Metadata Loader] Add the ability to download game screenshots

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/PlayniteExtensionsCollection#131]
**Extension**
Extra Metadata Tool Loader

**Describe the solution you'd like**
It would be great if this extension could be enhanced to download game screenshots from Steam if the API supports it. Theme developers would then be able to integrate this feature to display the screenshots alongside the game description. I think this would streamline the Playnite browsing experience since users would be able to see at a glance what a game actually looks like without having to load up the Steam Store page or watch any trailers.

- Give users the option to set a limit on the number of downloaded images per game.
- If themes can't find any stored images in the Extra Metadata directory, they should be able to call this plugin to download the images into a cache.

**Screenshots**
on of what the problem is.

**Comment by darklinkpower** [comment]
Sorry but I don't have plans for something like this. The issue is that it's not a matter of just downloading but also implementing the functionality, creating the controls to display the screenshots and everything needed and it's not an easy task. If someone wants to contribute and develop this functionality it will be welcomed but I personally can't add this.
