### ISSUE TITLE
[Installation Status Updater] Option to disable notifications

### ISSUE THREAD

**Issue by flzubuduuz** [darklinkpower/PlayniteExtensionsCollection#165]
### Extension name

Installation Status Updater

### Feature Description

Version 2.18 of Installation Status Updater made it so that the extension shows a notification every time your library is updated. I don't know if it would be possible to have the option to disable these notifications, because I would rather not have them pop up.
Thanks in advance!

**Comment by darklinkpower** [comment]
This notification only shows if there are changes made to games installation statuses. For example:

![image](https://user-images.githubusercontent.com/1389286/150608640-08b155ab-e7f5-4a94-83d6-4cb51d825b34.png)

If there aren't changes it is not shown so this means there are changes during execution after you update your library right? If that's the case, it is intended and its purpose is so people can know that the extension modified the installation status of games because it has already happened a few times that people ask for support for Playnite because their games are changing installation statuses and they don't know the extension did it.

**Comment by flzubuduuz** [comment]
> If there aren't changes it is not shown so this means there are changes during execution after you update your library right?

You're right, I didn't express myself correctly.


> If that's the case, it is intended

I understand this; I just wanted to know if there was a way of disabling these notifications, because I unplug and replug a hard drive with games really often, and dismissing the notification every time (when I know exactly what is happening) is a bit annoying.
No big deal if they can't be disabled though, this is very much a nitpick on my behalf.

**Comment by darklinkpower** [comment]
I don't like the idea of having an option to disable this behavior. It has been an issue several times that people need support and don't realize the extension did this but I've added a secret way to disable notifications. Create a file named `DisableNotifications` (without extension) in the plugin data directory

![image](https://user-images.githubusercontent.com/1389286/150657822-fc44b1dc-ca9d-4056-bcdf-5e5f4a4a9758.png)


![image](https://user-images.githubusercontent.com/1389286/150657791-efe86372-7a1f-40d3-b348-ec90f5c24f6d.png)

**Comment by flzubuduuz** [comment]
Works like a charm, thank you so much!
