### ISSUE TITLE
[Games Size Calculator] Run the size calculator on import?

### ISSUE THREAD

**Issue by Jhanlon95** [darklinkpower/PlayniteExtensionsCollection#192]
### Extension name

Games Size Calculator

### Feature Description

When importing new games into playnite it would be a nice QOL feature if the size calc could run, similar to how SuccessStory's will get achievements of games that have been imported if they are found. 

This would save me from forgetting to run it on the games after they've been imported and I wouldn't need to select every game in my library and update from that

**Comment by darklinkpower** [comment]
It's not possible to calculate this on import due to some issues. When Playnite detects the game as installed, the game could actually be in an unfinished download process so calculating the size would not work. You can test this by starting installation of a game handled by a plugin, like Steam, where Playnite will start the download process as soon as Steam starts downloading the game. The only way that I think could work is:
a) Detect installation state via game client files, like Steam manifest to detect installation state. This would be a lot of work that personally I'm not too eager to try to implement since this would need to be investigated for all the different clients out there and would require a lot of work.
b) Detect installation state after the first time you play the game. This would be relatively simple to implement and would be universal.

**Comment by Jhanlon95** [comment]
Hi Apologies for the late reply on this. I think either approach would be suitable. Personally I think option b) is better since it's less work and after you play the game then it doesn't even matter

**Comment by darklinkpower** [comment]
Added option to automatically calculate the game size after it is stopped in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/784d723ff7554ac81fe089a9d7955d49f6d980bb
