### ISSUE TITLE
[Game Size Calculator] Doesn't work for some games

### ISSUE THREAD

**Issue by OmarNamis** [darklinkpower/PlayniteExtensionsCollection#225]
### Extension name

Game Size Calculator

### Bug Description

The extension is working great, however, there are about 5 games out of my 300+ games collection that it did not work for.

The extension just says "Done", but the Version field remains empty, I double-checked the installation directory for these games, and everything seems fine.

One thing I found in common with these games is that they're local games (not from any store), and 3 of these games were downloaded from GOG, but I have other local games and GOG games as well, and they're calculated fine.

I'm not sure how I can go about troubleshooting this, so I'd be glad to help you with any more information you'd want from me.

### Extensions log

The log shows this line for each game that it worked for:

> |INFO |GamesSizeCalculator#GamesSizeCalculator:Updated * version field

But it shows nothing for the games that it didn't work for.

**Comment by darklinkpower** [comment]
Do these games have set in their Platforms one for PC? They need to be named `PC (Windows)` or have the specification Id set to PC, otherwise the extension will skip them. If this was the issue let me know if they had a different platform or if it was missing.

If the issue persists, rename this from zip to pext extension, install, select the problematic games and send me the log

[GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_13.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8404030/GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9_1_13.zip)

**Comment by OmarNamis** [comment]
Yes, that was it!
They were set to just "PC", so I changed them to "PC (Windows)" and that fixed the issue!

Thank you for your help!

**Comment by darklinkpower** [comment]
Did you manually set "PC" or was that added by a plugin? If that is the case, it should be reported that the new standard naming is "PC (Windows)" and that they should set the specification Id

![image](https://user-images.githubusercontent.com/1389286/161442439-e5a28857-0753-4d10-acf6-0c470558d35a.png)

You can also name the platform whatever you want and as long as it has the specification Id it will work. I'll add support for "PC" name only too.

**Comment by OmarNamis** [comment]
> Did you manually set "PC" or was that added by a plugin?

I'm not exactly sure, it must've been a long time ago. But I guess it was me.

> I'll add support for "PC" name only too.

That'd be great, thanks again for your help!
