### ISSUE TITLE
[Special K] Special K registry key not found

### ISSUE THREAD

**Issue by BoneofMalkav** [darklinkpower/PlayniteExtensionsCollection#276]
### Extension name

Special K

### Bug Description

Every time I launch a game on Steam or which I have set to run Special K's steam overlay (Specifically for non steam games like HoloCure: Save the Fans!) or try to open the profiles manager it keeps giving me the same error message. Which is weird because the installer for Special K never prompted me to put in a registry key. Nor did I ever find an option in the Playnite extention. Other then that the extention works fine but as mentioned keeps giving out that error pop up.

Special K version: 22.5.30
Frontend version: 0.9.8 (May 30 2022)

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9034934/extensions.log)

**Comment by darklinkpower** [comment]
I've added support to set the location of your Special K installation to solve this issue. This issue is happening since Special K added support to install it in portable mode, which doesn't create the registry key that is used by the extension to detect its location automatically

![image](https://user-images.githubusercontent.com/1389286/180621340-9baf31e5-c4d3-463e-a91a-b49324a0ea62.png)
