### ISSUE TITLE
[Game Pass Browser] Top bar button

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/PlayniteExtensionsCollection#308]
### Extension name

Game Pass Browser

### Feature Description

A button in the top bar that opens the game pass browser window

**Comment by limodual** [comment]
I second this! It would be really helpful and feels more integrated environment.

**Comment by Leah96xxx** [comment]
I also second this, but for the side bar instead. Would be nice to have options to enable top bar or side bar buttons to integrate the extension with the UI better, instead of having to dig through the menu just to browse the catalogue. Of course there is the option to just add all Game Pass games to the library, but that just makes my library feel cluttered so I'd rather have the catalogue in a separate tab.

**Comment by Jeshibu** [comment]
Actually having it as a separate view like the Playlist extension does would be a better idea, I agree.

**Comment by darklinkpower** [comment]
Sidebar view added in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/8ef17fcc5f8f0dde40e38684e9efcef7bf4f8357

**Comment by Jeshibu** [comment]
Thank you!
