### ISSUE TITLE
[Nexus Mods checker] Extension not loading

### ISSUE THREAD

**Issue by aherreracies** [darklinkpower/PlayniteExtensionsCollection#374]
### Extension name

Nexus Mods checker

### Bug Description

Everytime that I open Playnite, a message is displayed saying that the extension "Nexus Mods checker" failed to load properly. I checked for incompatibilities and there's none.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10862188/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10862189/extensions.log)

### Screenshots

![image](https://user-images.githubusercontent.com/67416451/222173901-77b241a8-e47c-42a7-9174-0dfaa8fa6645.png)

**Comment by darklinkpower** [comment]
This and [#373](https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/373) are not issues specific to the scripts, they are caused due to your system not being able to load the script files because it doesn't allow scripts that are not signed:

`System.Management.Automation.CmdletInvocationException: No se puede cargar el archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1. El archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1 no está firmado digitalmente. No se puede ejecutar este script en el sistema actual. Para obtener más información acerca de la ejecución de scripts y la configuración de la directiva de ejecución, consulta about_Execution_Policies en https:/go.microsoft.com/fwlink/?LinkID=135170. ---> System.Management.Automation.PSSecurityException: No se puede cargar el archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1. El archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1 no está firmado digitalmente. No se puede ejecutar este script en el sistema actual. Para obtener más información acerca de la ejecución de scripts y la configuración de la directiva de ejecución, consulta about_Execution_Policies en https:/go.microsoft.com/fwlink/?LinkID=135170. ---> System.UnauthorizedAccessException: No se puede cargar el archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1. El archivo C:\Playnite\Extensions\Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e\ExtraMetadataTools.psm1 no está firmado digitalmente. No se puede ejecutar este script en el sistema actual. Para obtener más información acerca de la ejecución de scripts y la configuración de la directiva de ejecución, consulta about_Execution_Policies en https:/go.microsoft.com/fwlink/?LinkID=135170.`

Have you modified any configuration related to that? From https:/go.microsoft.com/fwlink/?LinkID=135170, what do see if you use `Get-ExecutionPolicy -List` in Powershell? For example, this is what it says for me:

![image](https://user-images.githubusercontent.com/1389286/222289722-ceabb88c-719e-4d43-a3fd-5776fc05c5b2.png)

**Comment by darklinkpower** [comment]
Also open the Interactive SDK Powershell

![image](https://user-images.githubusercontent.com/1389286/222292199-ad38cfd0-5370-417d-af0e-9fbf5adb8ef9.png)

And use `Get-ExecutionPolicy`

![image](https://user-images.githubusercontent.com/1389286/222292259-93e607c0-6558-4b02-b1fc-99021f24ac51.png)

**Comment by darklinkpower** [comment]
After sharing what I indicate in the comments above, install this version and see if the issue is fixed for the Extra Metadata extension

[Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_12.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10866318/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_12.zip)

**Comment by aherreracies** [comment]
No, I haven't modified anything related to that. When I do what you said in Powershell it outputs this. Also, I installed the version that you shared and it didn't fix it
![image](https://user-images.githubusercontent.com/67416451/222377410-bb903749-3fb3-4048-8c0a-80fd6f1ec920.png)

**Comment by aherreracies** [comment]
> No, I haven't modified anything related to that. When I do what you said in Powershell it outputs this. Also, I installed the version that you shared and it didn't fix it ![image](https://user-images.githubusercontent.com/67416451/222377410-bb903749-3fb3-4048-8c0a-80fd6f1ec920.png)

Nevermind, looks like I fixed it by changing the execution policies in Powershell (following a tutorial). Thanks a lot for your help pointing me at the problem.

**Comment by darklinkpower** [comment]
Yeah the issue was your MachinePolicy. AllSigned is not the default and caused this issue.
