### ISSUE TITLE
[Steam Wishlist Discount Notifier] v1.26 not opening

### ISSUE THREAD

**Issue by Grogwort** [darklinkpower/PlayniteExtensionsCollection#458]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

As of latest update (1.26), upon launch attempt, the progress bar appears and then disappears, but the panel doesn't open.

Excerpt from extensions.log:
"08-11 09:30:59.347|ERROR|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Error while checking for wishlist
Newtonsoft.Json.JsonSerializationException: Error converting value "Advertising" to type 'SteamWishlistDiscountNotifier.Models.StoreItemType'. Path '34330.type', line 1, position 3923. ---> System.ArgumentException: Requested value 'Advertising' was not found."

### To Reproduce

Attempt to launch the extension.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13299755/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13299756/playnite.log)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/277c7242706a1c421645e94530f2974149e03ecf

The error is caused due to your wishlist containing an item of type "Advertising", which I have no idea what it is and I had not seen before. Please let me know if it's fixed for you to close the issue.

**Comment by Grogwort** [comment]
It is working correctly again in v1.27, thanks. 
I have no idea what item of type "Advertising" would be either. Weird.
