### ISSUE TITLE
[JastUsaLibrary] Error When Updating Library

### ISSUE THREAD

**Issue by burnpsy** [darklinkpower/PlayniteExtensionsCollection#540]
### Extension name

JastUsaLibrary

### Bug Description

Ever since I updated this extension to version 1.18, I get an error message when updating my library.

My account is authenticated properly, and just to make sure that wasn't the problem I authenticated it a second time.

### To Reproduce

Install version 1.18 of the extension, then try to update the library.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15376439/extensions.log)

### Screenshots

![Here's the error.](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/6007819/c7f9b0f2-15d4-4fb3-b0cf-c96f065d1d04)

**Comment by darklinkpower** [comment]
There's unfortunately nothing in the logs indicating this issue, is this still ocurring? If it does, please upload both Playnite.log and extensions.log after the error happens.

**Comment by burnpsy** [comment]
[playnite.log](https://github.com/user-attachments/files/15524402/playnite.log)
[extensions.log](https://github.com/user-attachments/files/15524403/extensions.log)

Was simple enough to make the error happen again (I just hit manual update on the JAST library), so I've attached the files you asked for.
The playnite.log seems to point to where the error is occurring.

**Comment by darklinkpower** [comment]
Delete both files to clean them. Then install this build and after reproducing the library update fails, upload both logs here again:

[JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_19.zip](https://github.com/user-attachments/files/15524428/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_19.zip)

**Comment by burnpsy** [comment]
[playnite.log](https://github.com/user-attachments/files/15524630/playnite.log)
[extensions.log](https://github.com/user-attachments/files/15524631/extensions.log)

New logs attached.

**Comment by darklinkpower** [comment]
Thanks. As a final request, can you go here:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/32bc24d6-b437-4230-931b-025f905dd17c)

And upload this file? I don't remember if GitHub allows upload of json so you may need to change the extension or upload in a zip.

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/54cb7352-8004-483b-82b1-5c252a7112b2)

**Comment by burnpsy** [comment]
Looks like I was allowed to upload it as-is:
[userGamesCache.json](https://github.com/user-attachments/files/15526109/userGamesCache.json)

**Comment by darklinkpower** [comment]
Thanks. The cause is that previously the plugin imported a game with id 114 but for some reason an entry with this id does not exist in the list of games JAST returns for your account. The only idea I have is maybe having refunded a game after having imported it to Playnite or unlikely, that you previously connected a different account, is that something that happened?

In any case, please try this build and send me the logs again after trying to update the library, it should indicate if this happened and it should work fine this time:

[JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_19.zip](https://github.com/user-attachments/files/15526666/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_19.zip)

If it works, please go to the plugin download manager here and check if you can add a few downloads without any issues just to be safe:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/b6f3c536-7bbf-45ad-b61a-cc01f34b09c9)

**Comment by burnpsy** [comment]
I didn't refund any games or add a second account, so I have to guess something got renumbered on JAST's end?

Either way, the version you just send ran without any apparent error, and I was able to add downloads from the menu you indicated, so problem solved.

**Comment by darklinkpower** [comment]
Can you upload the logs again please as I mentioned to see what happened?

**Comment by burnpsy** [comment]
[playnite.log](https://github.com/user-attachments/files/15526745/playnite.log)
[extensions.log](https://github.com/user-attachments/files/15526746/extensions.log)

**Comment by darklinkpower** [comment]
huh that's weird, there's no mention of the missing game if there was one. Did you delete the logs file after checking if it worked fine in this response?

If that's not the case, well, the second safeguard change I added will prevent any error.

**Comment by burnpsy** [comment]
I cleared the logs right after installing the newest version you sent me, then sent you everything that was generated since.

I did find it strange that nothing came up in the log this time at all.

**Comment by darklinkpower** [comment]
I see, can you send me this file?

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/f220bf37-2a65-4af8-b10d-74b0502a425d)


Or if you prefer, you can open it in your browser and just check if there's an entry with id `114` with `Ctrl+F` and tell me:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/26699fe8-d8dc-43ce-8f3a-437d11e68c3a)

**Comment by burnpsy** [comment]
[config.json](https://github.com/user-attachments/files/15526858/config.json)

Here you go. I'm not seeing anything with the GameId of 114.

Finding this strange, I went and manually compared my online JAST library to what's in Playnite. There were some manual additions (stuff where JAST lists two titles under one entry), but that's not managed by your extension. I could not identify anything missing other than non-games (uncensor patches, artbooks, etc. that obviously your extension doesn't add to the library).

**Comment by darklinkpower** [comment]
Thanks. It looks like the fix is working as intended and the problematic entry was correctly removed during library update since an entry with id 114 is not there, although I'm not sure why it wasn't logged.

Sorry for taking so long to work to fix this, it can be hard to maintain all addons I work on by myself. The release with the fix is already available.

Additionally, I recommend to delete your extensions.log file again since it contains a game download link that is only logged when using a debug build and that shouldn't be shared (and why I deleted your comment earlier), although those links are only valid for 48 hours if I recall correctly.
