### ISSUE TITLE
[VNDB Nexus] Space after tag prefix is sometimes trimmed

### ISSUE THREAD

**Issue by nikolay-borzov** [darklinkpower/PlayniteExtensionsCollection#569]
### Extension name

VNDB Nexus

### Bug Description

Trailing spaces in tag prefixes (except for "Content") are sometimes trimmed.

Consider settings for tags (notice spaces in the end):

Content Prefix: `[Content] `
Technical Prefix: `[Techical] `
Sexual Prefix: `[Sexual] `

But when metadata's fetched through "VNDB Nexus" I see:

![image](https://github.com/user-attachments/assets/d5ef873d-c984-42b0-8af1-b2a5d2919ef3)

Some tags are missing space between prefix and tag

### To Reproduce

1. Go to `Add-ons... > Extensions settings > Metadata Sources > VNDB Nexus`
2. Check `Metadata fields to obtain > Tags`
3. Check `Import` for `Content`, `Technical`, `Sexual`
4. Set prefixes with space at the end `[Content] `, `[Techical] `, `[Sexual] `
5. Save settings
6. Find a game that has page on VNDB or Add "Welcome To... Chichester OVN 1 : The Beach" game to library
7. Edit the game and click `Download Metadata... > VNDB Nexus`
8. Examine suggested tags

### Logs

[playnite.zip](https://github.com/user-attachments/files/16758665/playnite.zip)
[extensions.zip](https://github.com/user-attachments/files/16758668/extensions.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/b99557b1-1b8b-4330-9741-39fd70f7371a)

**Comment by nikolay-borzov** [comment]
Nevermind. It seems extension remembers assigned tags' IDs, so new suggested tags has the same name as existing ones

**Comment by darklinkpower** [comment]
That's very weird. The extension doesn't remember any id, it basically gives Playnite the list with the name of the tags to import and trimming is never performed. It just joins/concatenates the text you have configured with the name of the tag so in theory it should not be possible to have differences in the tags: https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/6ed1af21528a4349c53e0495556ef85b3509615b/source/Metadata/VNDBNexus/VNDBNexusMetadataProvider.cs#L569

I also just checked and I can't reproduce the issue with the problematic tags in your screenshot:

![image](https://github.com/user-attachments/assets/77378323-45ef-41c4-9da2-0a503ebc09fe)


What font are you using? I'm wondering if the issue is that the font you are using is not displaying the space properly despite being there, although that would be weird. If the issue remains please let me know.

**Comment by nikolay-borzov** [comment]
I use font [Jet Brains Mono](https://www.jetbrains.com/lp/mono/). 

There is no issue indeed.

Thanks for clarification!
