### ISSUE TITLE
[Steam Store Screenshots Viewer] Not visible after updating to Stardust 2.67

### ISSUE THREAD

**Issue by fm-117** [darklinkpower/PlayniteExtensionsCollection#573]
### Extension name

Steam Store Screenshots Viewer

### Bug Description

Compatibility with Steam Store Screenshots Viewer seems broken after updating to latest Stardust version.
The tab for screenshots is simply not displayed anymore.

### To Reproduce

Use both Stardust 2.67 and Steam Store Screenshots Viewer 1.6, then check detail view for screenshots

### Logs

[playnite.log](https://github.com/user-attachments/files/17085278/playnite.log)
[extensions.log](https://github.com/user-attachments/files/17085280/extensions.log)
playnite.log truncated to keep only today's logs

**Comment by darklinkpower** [comment]
That's weird, I don't see anything in the theme that could possibly cause this. Can you share a screenshot of what you are seeing? Is the tab here not displayed for you?

![image](https://github.com/user-attachments/assets/37b4d3c6-b26c-41c6-ade4-1b890db29057)

Do the screenshots display fine in other themes like Mythic or Harmony?

**Comment by darklinkpower** [comment]
Nevermind, I see the issue in the logs:

```
C:\Users\LeCharlatan\AppData\Roaming\Playnite\ExtensionsData\8e77fe31-5e62-41e2-8fa2-64844cfd5b6b\appdetails\67370_appdetails.json is not successful
```

The game is The Darkness II. The problem is that Steam is returning invalid data and when the plugin detects this, it deletes the file and redownloads it again when you select the game again afterwards in hopes that Steam returns data. If the issue remains, the only solution is waiting some time, I don't know why but Steam eventually returns the correct data.

**Comment by fm-117** [comment]
I expected the screenshots tab to appear on the right of the Descripton tab but now I see it, they are below the game card just like in your screenshot. Closing the issue.
