### ISSUE TITLE
[Nvidia Geforce Now Library] Extension Failed to Load properly

### ISSUE THREAD

**Issue by Zybun** [darklinkpower/PlayniteExtensionsCollection#594]
### Extension name

Nvida Geforce Now Library

### Bug Description

Upon starting playnite with the library already installed, user recieves notification saying `Extension "NVIDIA Geforce Now Library" failed to load properly` and the library does not function. It does not appear in the "Update Game Library" list alongside other libraries like steam and epic etc nor does it appear in the extensions tab. It is as though the addon is simply inactive.

### To Reproduce

Unclear how to reproduce. Tried disabling/removing all other addons/themes to see if a particular extension is causing issues, but no luck.

### Logs

[extensions.log](https://github.com/user-attachments/files/18000507/extensions.log)
[playnite.log](https://github.com/user-attachments/files/18000508/playnite.log)

**Comment by darklinkpower** [comment]
Can you upload your `gfnDatabase.json` file from here please?

![Playnite DesktopApp_B7qKY9aa0h](https://github.com/user-attachments/assets/7e3b044f-ac36-4042-9ef8-d3d71cb343f2)

**Comment by Zybun** [comment]
No I cannot. When I click that button, nothing happens.

**Comment by darklinkpower** [comment]
> No I cannot. When I click that button, nothing happens.

Oh yeah there's a bug in Playnite where the button doesn't work if the plugin is disabled.

The reason of the crash is that the file became corrupted, it was written incompletely. This can happen for many reasons, like unexpected process shutdown, insufficient space, etc.

![image](https://github.com/user-attachments/assets/4cc6de33-e307-45e1-a2ef-f01847951b85)

Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/18d033e9a5ecba991f74b7edf07403122289da34. Available in new update.
