### ISSUE TITLE
[ExtraMetadataLoader] Stream steam trailers on demand

### ISSUE THREAD

**Issue by felixkmh** [darklinkpower/PlayniteExtensionsCollection#60]
**Extension**
ExtraMetadataLoader

**Describe the solution you'd like**
You could set the `Source` of the MediaElement to the url of the .mp4 steam trailer if there is no local copy of it. Users should be able to enable/disable this behaviour in the settings.

**Comment by darklinkpower** [comment]
Done in a commit that I can't upload.

Just as side info, the Crowdin project for this repository is currently having severe issues. Broken localization strings are being pushed automatically, PRs and strings are not updating properly and I can't access some features due to issues on their side

![image](https://user-images.githubusercontent.com/1389286/135449159-d31836de-b8ad-455a-b81f-1755c51d9dce.png)

So I'll be closing this issue once I upload the related commit since I don't want to change anything in the repository so their developers can investigate the issue without interference.

**Comment by darklinkpower** [comment]
I changed my mind since I don't have an idea of how much time they'll take to fix it, although I won't be updating localizations until then. Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/10c872522fcdb01d28e9e022862ef46f129479d6.
